spring:
  data:
    mongodb:
      host: 172.17.0.3
      port: 27017
      database: library

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw08mongo.mongock.changelog
