server:
  port: 8081

  data:
    mongodb:
      host: 0.0.0.0
      port: 27017
      database: library

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw09thymeleaf.changelog
