DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS GENRE;
CREATE TABLE BOOK(ID BIGINT PRIMARY KEY, NAME VARCHAR(255), AUTHOR_ID BIGINT, GENRE_ID BIGINT);
CREATE TABLE AUTHOR(ID BIGINT PRIMARY KEY, NAME VARCHAR(255), SURNAME VARCHAR(255));
CREATE TABLE GENRE(ID BIGINT PRIMARY KEY, NAME VARCHAR(255));